name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: install packages
      run: brew install cmake curl openssl
    - name: configure
      # Paths are required as brew won't install openssl to system directories
      run: cmake cmake -DCMAKE_CXX_FLAGS=-I /usr/local/opt/openssl@3/include -DCMAKE_CXX_FLAGS=-L /usr/local/opt/openssl@3/lib .
    - name: make
      run: make
    
