name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: install packages
      run: sudo apt-get install cmake libssl-dev libcurl4-gnutls-dev
    - name: configure
      run: cmake .
    - name: make
      run: make
    
